####   1  .The historical average score in a certification exam is 65. A training institute introduces a new course. A random sample of 50 students trained under the new course has an average score of 68. At the 5% level of significance, test whether the new course improves performance.

In [1]:

import numpy as np
from scipy import stats

population_mean = 65       
sample_mean = 68           
sample_size = 50
sample_std = 10            
alpha = 0.05               

# Perform one-sample t-test (one-tailed)
# t-statistic = (sample_mean - population_mean) / (sample_std / sqrt(n))
t_stat = (sample_mean - population_mean) / (sample_std / np.sqrt(sample_size))

# Degrees of freedom
df = sample_size - 1

# Calculate p-value for one-tailed test
p_value = 1 - stats.t.cdf(t_stat, df=df)

# Print results
print(f"t-statistic: {t_stat:.4f}")
print(f"p-value: {p_value:.4f}")

# Decision
if p_value < alpha:
    print("Reject the null hypothesis: The new course improves performance.")
else:
    print("Fail to reject the null hypothesis: No significant improvement.")

t-statistic: 2.1213
p-value: 0.0195
Reject the null hypothesis: The new course improves performance.


#### 2 . A company claims that the average time taken to resolve customer tickets is 30 minutes.A random sample of 40 tickets shows a mean resolution time of 33 minutes. At the 5% level of significance, test whether the average resolution time has increased.

In [2]:
import numpy as np
from scipy import stats

# Given data
population_mean = 30       # claimed average resolution time
sample_mean = 33           # sample mean
sample_size = 40
sample_std = 5             # assume sample std deviation (if not given, estimate from data)
alpha = 0.05               # significance level

# t-statistic calculation
t_stat = (sample_mean - population_mean) / (sample_std / np.sqrt(sample_size))

# Degrees of freedom
df = sample_size - 1

# p-value for one-tailed test
p_value = 1 - stats.t.cdf(t_stat, df=df)

# Print results
print(f"t-statistic: {t_stat:.4f}")
print(f"p-value: {p_value:.4f}")

# Decision
if p_value < alpha:
    print("Reject the null hypothesis: Average resolution time has increased.")
else:
    print("Fail to reject the null hypothesis: No significant increase.")

t-statistic: 3.7947
p-value: 0.0003
Reject the null hypothesis: Average resolution time has increased.


#### 3. A company claims that 60% of its users are satisfied with its product. In a survey of 200 users, 134 users report satisfaction. At the 5% level of significance, test whether customer satisfaction is higher than claimed.

In [6]:
import numpy as np

from statsmodels.stats.proportion import proportions_ztest

# Given data
claimed_proportion = 0.60
sample_size = 200
success_count = 134  # number of satisfied users
alpha = 0.05         

# Perform one-sample z-test for proportions
# alternative='larger' because we are testing if proportion is higher
z_stat, p_value = proportions_ztest(count=success_count, nobs=sample_size, value=claimed_proportion, alternative='larger')

# Print results
print(f"z-statistic: {z_stat:.4f}")
print(f"p-value: {p_value:.4f}")

# Decision
if p_value < alpha:
    print("Reject the null hypothesis: Customer satisfaction is higher than claimed.")
else:
    print("Fail to reject the null hypothesis: No significant increase in satisfaction.")

z-statistic: 2.1053
p-value: 0.0176
Reject the null hypothesis: Customer satisfaction is higher than claimed.


#### 4. Historically, 40% of applicants pass an entrance test. After a new preparation program, 90 out of 180 applicants pass. Test at the 5% level of significance whether the pass rate has improved.

In [7]:
import numpy as np
from scipy.stats import norm

# Given data
historical_rate = 0.40
sample_size = 180
success_count = 90
alpha = 0.05

# Sample proportion
p_hat = success_count / sample_size

# z-statistic
z_stat = (p_hat - historical_rate) / np.sqrt(historical_rate * (1 - historical_rate) / sample_size)

# p-value for one-tailed test
p_value = 1 - norm.cdf(z_stat)

# Print results
print(f"Sample proportion: {p_hat:.4f}")
print(f"z-statistic: {z_stat:.4f}")
print(f"p-value: {p_value:.4f}")

# Decision
if p_value < alpha:
    print("Reject the null hypothesis: Pass rate has improved.")
else:
    print("Fail to reject the null hypothesis: No significant improvement in pass rate.")

Sample proportion: 0.5000
z-statistic: 2.7386
p-value: 0.0031
Reject the null hypothesis: Pass rate has improved.


####  5. Two teaching methods are used to train employees. A sample of 30 employees trained using Method A and 28 employees trained using Method B are tested. Test at the 5% level of significance whether there is a difference in average scores between the two methods.

In [8]:
import numpy as np
from scipy import stats

# Example data (replace these with actual sample means and std devs if available)
# Sample 1 (Method A)
sample_A = [78, 82, 85, 79, 81, 77, 84, 80, 76, 83,
            85, 79, 81, 80, 78, 82, 84, 79, 77, 81,
            80, 78, 82, 85, 79, 81, 80, 78, 83, 84]

# Sample 2 (Method B)
sample_B = [75, 79, 80, 78, 77, 76, 81, 78, 75, 80,
            79, 77, 78, 76, 75, 79, 80, 77, 78, 76,
            77, 79, 80, 78, 76, 77, 79, 78]

alpha = 0.05  # significance level

# Perform two-sample t-test (Welch's t-test)
t_stat, p_value = stats.ttest_ind(sample_A, sample_B, equal_var=False)

# Print results
print(f"t-statistic: {t_stat:.4f}")
print(f"p-value: {p_value:.4f}")

# Decision
if p_value < alpha:
    print("Reject the null hypothesis: There is a significant difference between the two methods.")
else:
    print("Fail to reject the null hypothesis: No significant difference between the two methods.")

t-statistic: 5.0955
p-value: 0.0000
Reject the null hypothesis: There is a significant difference between the two methods.


#### 6. The average delivery time from Warehouse A and Warehouse B is compared using random samples from both warehouses. At the 5% level of significance, test whether the mean delivery times differ.

In [9]:
import numpy as np
from scipy import stats

# Example data (replace these with your actual sample data)
# Delivery times from Warehouse A (in hours)
warehouse_A = [5.2, 4.8, 5.5, 5.0, 5.1, 4.9, 5.3, 5.2, 5.0, 5.1]

# Delivery times from Warehouse B (in hours)
warehouse_B = [5.5, 5.7, 5.6, 5.8, 5.4, 5.6, 5.5, 5.7, 5.6, 5.5]

alpha = 0.05  # significance level

# Perform two-sample t-test (Welch's t-test)
t_stat, p_value = stats.ttest_ind(warehouse_A, warehouse_B, equal_var=False)

# Print results
print(f"t-statistic: {t_stat:.4f}")
print(f"p-value: {p_value:.4f}")

# Decision
if p_value < alpha:
    print("Reject the null hypothesis: Mean delivery times are significantly different.")
else:
    print("Fail to reject the null hypothesis: No significant difference in mean delivery times.")

t-statistic: -6.4528
p-value: 0.0000
Reject the null hypothesis: Mean delivery times are significantly different.


#### 7. 7. Two versions of a website are tested. Out of 500 users for Version A, 320 users click the signup button. Out of 480 users for Version B, 290 users click the signup button. At the 5% level of significance, test whether the conversion rates differ.

In [10]:
# Import required library
from statsmodels.stats.proportion import proportions_ztest

# Data
count = [320, 290]   # number of successes for Version A and B
nobs = [500, 480]    # total users for Version A and B
alpha = 0.05

# Perform two-proportion z-test (two-tailed by default)
z_stat, p_value = proportions_ztest(count, nobs, alternative='two-sided')

# Print results
print(f"z-statistic: {z_stat:.4f}")
print(f"p-value: {p_value:.4f}")

# Decision
if p_value < alpha:
    print("Reject the null hypothesis: Conversion rates differ significantly.")
else:
    print("Fail to reject the null hypothesis: No significant difference in conversion rates.")

z-statistic: 1.1568
p-value: 0.2474
Fail to reject the null hypothesis: No significant difference in conversion rates.


#### 8. A vaccine is tested in two regions. In Region A, 180 out of 300 people recover. In Region B, 165 out of 310 people recover. Test whether the recovery rates are significantly different.

In [11]:
# Import required library
from statsmodels.stats.proportion import proportions_ztest

# Data
count = [180, 165]   # number of recoveries in Region A and B
nobs = [300, 310]    # total people in Region A and B
alpha = 0.05

# Perform two-proportion z-test (two-tailed)
z_stat, p_value = proportions_ztest(count, nobs, alternative='two-sided')

# Print results
print(f"z-statistic: {z_stat:.4f}")
print(f"p-value: {p_value:.4f}")

# Decision
if p_value < alpha:
    print("Reject the null hypothesis: Recovery rates are significantly different.")
else:
    print("Fail to reject the null hypothesis: No significant difference in recovery rates.")

z-statistic: 1.6875
p-value: 0.0915
Fail to reject the null hypothesis: No significant difference in recovery rates.


#### 9. A company wants to compare the average productivity of employees trained using three different training programs. At the 5% level of significance, test whether there is a difference in mean productivity across the programs.

In [12]:
import numpy as np
from scipy.stats import f_oneway

# Example data (replace with actual productivity scores)
program_A = [75, 80, 78, 82, 77, 79]
program_B = [85, 87, 90, 88, 86, 89]
program_C = [78, 81, 79, 80, 77, 82]

alpha = 0.05

# Perform one-way ANOVA
F_stat, p_value = f_oneway(program_A, program_B, program_C)

# Print results
print(f"F-statistic: {F_stat:.4f}")
print(f"p-value: {p_value:.4f}")

# Decision
if p_value < alpha:
    print("Reject the null hypothesis: There is a significant difference in mean productivity among the programs.")
else:
    print("Fail to reject the null hypothesis: No significant difference in mean productivity.")

F-statistic: 33.9535
p-value: 0.0000
Reject the null hypothesis: There is a significant difference in mean productivity among the programs.


#### 10. A company wants to test whether gender and product preference are independent. A contingency table is created using survey data. At the 5% level of significance, test for independence.

In [13]:
import numpy as np
from scipy.stats import chi2_contingency

# Contingency table (replace with actual survey data)
# Rows: Gender, Columns: Product preference
data = np.array([[30, 20, 50],
                 [40, 25, 35]])

alpha = 0.05

# Perform Chi-Square Test of Independence
chi2_stat, p_value, dof, expected = chi2_contingency(data)

# Print results
print(f"Chi-Square statistic: {chi2_stat:.4f}")
print(f"Degrees of freedom: {dof}")
print(f"p-value: {p_value:.4f}")
print("Expected frequencies:")
print(expected)

# Decision
if p_value < alpha:
    print("Reject the null hypothesis: Gender and product preference are dependent.")
else:
    print("Fail to reject the null hypothesis: Gender and product preference are independent.")

Chi-Square statistic: 4.6312
Degrees of freedom: 2
p-value: 0.0987
Expected frequencies:
[[35.  22.5 42.5]
 [35.  22.5 42.5]]
Fail to reject the null hypothesis: Gender and product preference are independent.


#### 11. A hospital studies whether smoking status is related to disease occurrence. Test whether the two variables are independent.

In [14]:
import numpy as np
from scipy.stats import chi2_contingency

# Contingency table (replace with actual hospital data)
# Rows: Smoking status, Columns: Disease occurrence
data = np.array([[50, 30],
                 [20, 40]])

alpha = 0.05

# Perform Chi-Square Test of Independence
chi2_stat, p_value, dof, expected = chi2_contingency(data)

# Print results
print(f"Chi-Square statistic: {chi2_stat:.4f}")
print(f"Degrees of freedom: {dof}")
print(f"p-value: {p_value:.4f}")
print("Expected frequencies under independence:")
print(expected)

# Decision
if p_value < alpha:
    print("Reject the null hypothesis: Smoking status and disease occurrence are dependent.")
else:
    print("Fail to reject the null hypothesis: Smoking status and disease occurrence are independent.")

Chi-Square statistic: 10.5292
Degrees of freedom: 1
p-value: 0.0012
Expected frequencies under independence:
[[40. 40.]
 [30. 30.]]
Reject the null hypothesis: Smoking status and disease occurrence are dependent.


#### 12 .  A dice manufacturer claims that a die is fair. The die is rolled 120 times, and observed frequencies are recorded. Test at the 5% level of significance whether the die is fair.